### PR TITLE
msdk: free mfx frames to avoid memory leaks in encoder and vpp

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Comment by xhaihao** [comment]
@uartie @zhoujd I didn't see failure case in the log, why did pre-check fail?

`02:57:52,843 INFO  - = Session ended. 144 successful, 2 skipped, 0 failed, 0 erroneous. Total duration: 00:02:10 =`

**Comment by uartie** [comment]
> @uartie @zhoujd I didn't see failure case in the log, why did pre-check fail?
> 
> `02:57:52,843 INFO - = Session ended. 144 successful, 2 skipped, 0 failed, 0 erroneous. Total duration: 00:02:10 =`

It was a network interruption.  I have queued it again.

**Comment by uartie** [comment]
> > @uartie @zhoujd I didn't see failure case in the log, why did pre-check fail?
> > `02:57:52,843 INFO - = Session ended. 144 successful, 2 skipped, 0 failed, 0 erroneous. Total duration: 00:02:10 =`
> 
> It was a network interruption. I have queued it again.

Error message on "build overview" page:
```
master>Test Pull Request@media-build-02:18801
Error executing step process job.
caused by: Error executing step execution job.
caused by: java.net.UnknownHostException: media-ci.ostc.intel.com
caused by: media-ci.ostc.intel.com
```

**Comment by xhaihao** [comment]
@uartie  thanks a lot.

**Comment by xhaihao** [comment]
passed.

**Pull request closed without merging**
