### PR TITLE
Msdk dec return value

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Comment by xhaihao** [comment]
@zhoujd @uartie  A recent commit (e9c68347f0c82dc09cc2411196d9a56d60e4591e) caused a compiler error on xenial, could you disable curlhttpsrc in build if curlhttpsrc is not used in ci?

**Comment by uartie** [comment]
I don't think we use this element.   @zhoujd please disable it in CI configuration with the "extra_config_args" variable.

**Comment by uartie** [comment]
It can be disabled with `-Dcurl=disabled`

**Comment by zhoujd** [comment]
Thanks, will do the change.

**Comment by zhoujd** [comment]
Done to change on CI server side.

**Comment by xhaihao** [comment]
Thanks @zhoujd

**Comment by xhaihao** [comment]
Check passed!

**Pull request closed without merging**
