### PR TITLE
msdkh265enc: add support for screen content coding

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Comment by xhaihao** [comment]
@uartie I see an error about line21 in the pre-check. Is it possible to ignore such error?

12:38:22,844 INFO  - ../tests/check/elements/line21.c:80:F:general:basic:0: Assertion 'in_cc_meta != out_cc_meta' failed
12:38:22,844 INFO  - Check suite line21 ran in 0.009s (tests failed: 1)

**Comment by uartie** [comment]
> @uartie I see an error about line21 in the pre-check. Is it possible to ignore such error?
> 
> 12:38:22,844 INFO - ../tests/check/elements/line21.c:80:F:general:basic:0: Assertion 'in_cc_meta != out_cc_meta' failed
> 12:38:22,844 INFO - Check suite line21 ran in 0.009s (tests failed: 1)

I'm not sure how to filter out specific gstreamer unit tests.  I would have to experiment.  But, I don't know if it's worth the effort.  It's probably better to just report and have upstream fix the problem.

In the meantime, I think it's fine for you to ignore any failures that are not caused by your patches.

**Comment by uartie** [comment]
It appears there is no way to skip specific unit test cases at runtime.  So, FWIW, I submitted https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1388

**Comment by uartie** [comment]
@xhaihao I think I found reasonable solution to skip specific meson tests.  See my comment on our internal gitlab MR.

**Comment by xhaihao** [comment]
Thanks @uartie , I closed this MR as there aren't other bugs in the pre-check.

**Pull request closed without merging**
