### PR TITLE
Fix memory issues

### PR DESCRIPTION
**Pull request by xhaihao**
This fixes https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1516

### CODE REVIEW

**Comment by uartie** [comment]
@xhaihao what's the status of this PR?

**Comment by xhaihao** [comment]
@uartie Thanks for reminding me, I updated the patch and will close this PR once it passes the check.

**Comment by xhaihao** [comment]
@uartie I didn't see failed case, could you please help to check why intel/ci/ubuntu/bionic/pr/check do not pass the check?

**Comment by uartie** [comment]
> @uartie I didn't see failed case, could you please help to check why intel/ci/ubuntu/bionic/pr/check do not pass the check?

Please look at the steps https://media-ci.ostc.intel.com/build/564630/step_status.  In particular look at the unit test step "log".  The unit tests don't conform to junit output, thus they don't show up in the Junit test reports.

**Comment by uartie** [comment]
> > @uartie I didn't see failed case, could you please help to check why intel/ci/ubuntu/bionic/pr/check do not pass the check?
> 
> Please look at the steps https://media-ci.ostc.intel.com/build/564630/step_status. In particular look at the unit test step "log". The unit tests don't conform to junit output, thus they don't show up in the Junit test reports.

That is, the unit tests can't be summarized in a QB test report since gstreamer doesn't use a common, standard test output .  So we just run the unit tests in a step without generating a report summary.  But, the step fails because the unit test command failed.  You can see test command details in the step log.

**Comment by xhaihao** [comment]
It seems the error is not by this PR.  Only `elements_msdkh264enc` is msdk related, however the error occurred before `elements_msdkh264enc`

**Comment by uartie** [comment]
> It seems the error is not caused by this PR. Only `elements_msdkh264enc` is msdk related, however the error occurred before `elements_msdkh264enc`

Yeh, probably not caused by this PR, but we should track it down.  Did you try locally?

**Comment by uartie** [comment]
FWIW, this PR last succeeded here https://media-ci.ostc.intel.com/build/555974/step_status, then next run failed here https://media-ci.ostc.intel.com/build/556018/step_status.  The only change in this next run was in -good dependency at https://media-ci.ostc.intel.com/build/556011/scm_changes.  All checks after this failed.  Hope this gives a clue.

**Comment by uartie** [comment]
Looks like CI runs cases in random listed order and possibly parallel.  So the unit failure log is different each time.  We might try sorting the case list and run sequentially to see if it helps pin down the cause.

**Comment by uartie** [comment]
Nonetheless, if we can't trust the unit tests to be reliably managed in upstream, then we shouldn't run them in PR.

**Comment by xhaihao** [comment]
I may run `unit` test locally successfully w/wo https://media-ci.ostc.intel.com/build/556011/scm_changes

**Comment by xhaihao** [comment]
is there a timer in PR check ? `elements_camerabin` consumed 54+s in my testing.

**Comment by xhaihao** [comment]
I did nothing except adding a blank line in https://github.com/intel-media-ci/gst-plugins-bad/pull/83 which failed too.

**Comment by uartie** [comment]
I discovered another change... we updated our base bionic docker image and this is when it started failing.  I will investigate.

This patch is not the issue.

**Comment by uartie** [comment]
> I discovered another change... we updated our base bionic docker image and this is when it started failing. I will investigate.
> 
> This patch is not the issue.

Ok, the problem is that a new version of meson added some extra test log output that is using utf-8 characters that can't be encoded to ascii (i.e. ordinal range > 128).  This is crashing our python scripts.  Python is using ascii IO encoding by default.

In old image, meson == 0.55.3
In new image, meson == 0.57.1

If I set `PYTHONIOENCODING=UTF8` it works.  Or, if I downgrade meson in new image to 0.55.3 it works.

In particular, the new meson version prints lines like:

――――――――――――― ✀  ――――――――――

I will update our python scripts to handle utf-8 strings better.

**Comment by uartie** [comment]
AFAICT, the best solution from the web is to set PYTHONIOENCODING=UTF8 .  Thus, I have added this to our CI for gst pre-checks.

**Comment by uartie** [comment]
Checks Pass.  Close.

**Comment by uartie** [comment]
FWIW, focal and groovy images have `LC_CTYPE=C.UTF-8` preset.  But bionic image does not.  Setting this in bionic image also fixes it.

**Comment by xhaihao** [comment]
@uartie Many thanks for fixing this annoying issue.

**Pull request closed without merging**
